### ISSUE TITLE
SuperNode Code Generator throws error from "using static" syntax

### ISSUE THREAD

**Issue by RevyaS** [chickensoft-games/SuperNodes#17]
If the SuperNode class contains a 'using static' syntax, it will throw this error when building the project.

CS0138: A 'using namespace' directive can only be applied to namespaces; 'StaticClass' is a type not a namespace. Consider a 'using static' directive instead

Here's the minimal reproduction project. Just the main.cs containing 'using static' syntax for the static class. Removing it and its references will build just fine.
[SuperNodeStaticUsingIssue.zip](https://github.com/chickensoft-games/SuperNodes/files/13802493/SuperNodeStaticUsingIssue.zip)

**Comment by jolexxa** [comment]
Thanks for reporting!
